#:schema node_modules/wrangler/config-schema.json
name = "idees"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

# Automatically place your workloads in an optimal location
# https://developers.cloudflare.com/workers/configuration/smart-placement/
[placement]
mode = "smart"

# Assets configuration for static files
[assets]
directory = ".open-next/assets"
binding = "ASSETS"
